server:
  port: 8080
  tomcat:
    connection-timeout: 60000

spring:
  application:
    name: VibeWave
  datasource:
    url:  jdbc:postgresql://localhost:5432/VibeWave
    username: postgres
    password: gfhjkm12
  jpa:
    hibernate:
      show-sql: true
      generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-1.yaml
    enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  accessExpirationTime: 900000 #15 минут
  refreshExpirationTime: 604800000 #1 неделя
minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: password
  bucket: user-media
