spring:
  application:
    name: VibeWave
  datasource:
    url:  jdbc:postgresql://localhost:5432/VibeWave
    username: postgres
    password: gfhjkm12
  jpa:
    hibernate:
      show-sql: true
      generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-1.yaml
    enabled: true
jwt:
  secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  accessExpirationTime: 900000 #15 минут
  refreshExpirationTime: 604800000 #1 неделя